/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x18114245
 */
public class entitelementGUI extends javax.swing.JFrame {

    /**
     * Creates new form entitelementGUI
     */
    tax p;
    taxGUI g;
    entitelement e;
    int age;
    Double expenses;

    public ArrayList<tax> aList2 = new ArrayList();
    //.addAll(copyArrayofList);
    //List<T> newList = List.copyOf(oldList);
   
    public entitelementGUI() {

        initComponents();

    }

    public entitelementGUI(tax p, taxGUI g, entitelement e) {
        this.p = p;
        this.g = g;
        this.e = e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        kids = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        expensesTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        entitlments = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nationality = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        residency = new javax.swing.JComboBox<>();
        ADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("marital statut");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[please select your status]", "single", "married", "divorced", "widowed" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel3.setText("dependants");

        kids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[plese selectc number of kids you have]", "0", "1", "2", "3", "4", "more" }));
        kids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidsActionPerformed(evt);
            }
        });

        jLabel1.setText("please enter your total weekly expanses");

        jLabel4.setText("age");

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });

        entitlments.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        entitlments.setText("My Entitlements");
        entitlments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entitlmentsActionPerformed(evt);
            }
        });

        jButton1.setText("more info?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irish", "EU", "EEA", "Swiss", "stamp 4", "non of the above" }));
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });

        jLabel5.setText("Nationality ");

        jLabel6.setText("Residency in Ireland, the EU, EEA or Switzerland");

        residency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "less than 3 years out of last 5 years", "more than 3 yearsout of last 5 years" }));
        residency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencyActionPerformed(evt);
            }
        });

        ADD.setText("Add");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expensesTF)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(residency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(entitlments))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(expensesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(residency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(ADD)
                .addGap(18, 18, 18)
                .addComponent(entitlments)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void entitlmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entitlmentsActionPerformed

        readFromFile();

        // if u want to call the weekly netpay use  aList2.get(i).netpay();
        // if u want to call the monthly  netpay use aList2.get(i).netpay1();
        //if u wnat to call annual netpay use aList2.get(i).netpay2();
        //                                                 just texting the funtion here 
        
        

        /*                                          susi entitlment 
        for (int i = 0; i < aList2.size(); i++) {

            aList2.get(i).weekly();     // add this line in other GUI
            aList2.get(i).annual();       // add this line in other GUI also
            aList2.get(i).netpay2();

        }
        */                                      //   Medical card entitlment 

        aList2.get(aList2.size() -1).weekly();
            aList2.get(aList2.size() -1).monthly();

                  // add this line in other GUI also
            aList2.get(aList2.size() -1).netpay2();
            if (age < 66 && aList2.get(aList2.size() -1).netpay() < 266.50 && ((kids.getSelectedIndex() == 2) || (kids.getSelectedIndex() == 3) || (kids.getSelectedIndex() == 4))) {
                JOptionPane.showMessageDialog(null, "you are eligible" + aList2.get(aList2.size() -1).netpay() + "to Medical card  if u have dependants and ur weekly income less than 266.50");
            } else if (age < 66 && aList2.get(aList2.size() -1).netpay() < 184.00 && ((kids.getSelectedIndex() == 1))) {
                JOptionPane.showMessageDialog(null, "you are eligible to Medical card  if u r single and ur weekly income less than 184.00");
            } else if (age > 66 && aList2.get(aList2.size() -1).netpay() < 173.50 && ((kids.getSelectedIndex() == 1))) {
                JOptionPane.showMessageDialog(null, "you are eligible to Medical card  if u r single and  older than 66 ur weekly income less than 173.50");
            } else if (age > 66) {
            }
            else if(aList2.get(aList2.size() -1).netpay()>266.50){
                JOptionPane.showMessageDialog(null, "needs more work ");
            }

        //                                                HAP
        for (int i = 0; i < aList2.size(); i++) {

            aList2.get(i).weekly();     // add this line in other GUI
            aList2.get(i).annual();       // add this line in other GUI also
            aList2.get(i).netpay2();

        }

        //                                         social housing
        for (int i = 0; i < aList2.size(); i++) {

            aList2.get(i).weekly();     // add this line in other GUI
            aList2.get(i).annual();       // add this line in other GUI also
            aList2.get(i).netpay2();

        }

        //                                      working family income
        for (int i = 0; i < aList2.size(); i++) {

            aList2.get(i).weekly();     // add this line in other GUI
            aList2.get(i).annual();       // add this line in other GUI also
            aList2.get(i).netpay2();

        }

        if (((status.getSelectedIndex() == 1) || (status.getSelectedIndex() == 2) || (status.getSelectedIndex() == 3))
                && (nationality.getSelectedIndex() == 0) || (nationality.getSelectedIndex() == 1) || (nationality.getSelectedIndex() == 2) || (nationality.getSelectedIndex() == 3) || (nationality.getSelectedIndex() == 4)) {

            JOptionPane.showMessageDialog(null, "you are entitled to  susi :");
        } else if ((nationality.getSelectedIndex() == 5)) {
            JOptionPane.showMessageDialog(null, "you are not eligible");
        }


    }//GEN-LAST:event_entitlmentsActionPerformed

    private void residencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residencyActionPerformed

    private void kidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidsActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "net");

        for (int i = 0; i < aList2.size(); i++) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed

        /*  age= Integer.parseInt(ageTF.getText());
        //expenses= Double.parseDouble(expensesTF.getText());
        e.setAge(age);
        //e.setWeeklyexpenses(expenses);
        aList2.add(e);*/

    }//GEN-LAST:event_ADDActionPerformed

    public void readFromFile() {
        try {
            File a = new File("output.dat");
            FileInputStream b = new FileInputStream(a);
            ObjectInputStream c = new ObjectInputStream(b);
            // read the object from the file  array of object here called Log
            // convert prob   > cast it to remind it is a employee
            aList2 = (ArrayList<tax>) c.readObject();
            c.close();

        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entitelementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entitelementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entitelementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entitelementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entitelementGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton entitlments;
    private javax.swing.JTextField expensesTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> kids;
    private javax.swing.JComboBox<String> nationality;
    private javax.swing.JComboBox<String> residency;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
