/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxapp;




import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x18114245
 */
public class taxGUI extends javax.swing.JFrame {
   

    
    String ppsnumber;
    Double usc, netpay, healthInsurance, taxCredit, unionSubs, prsi, overTime;
    Double gross, hours, rate;
    int count = 0; //set initial COUNT value to zero

    tax p;
    public ArrayList<tax> aList = new ArrayList();

    public taxGUI() {
        initComponents();
        
        
        
        readFromFile();

        hs.setVisible(false);
        hf.setVisible(false);

        tarifaLbl.setVisible(false);

        tauxLbl.setVisible(false);

        seguroLbl.setVisible(false);
        assuranceLbl.setVisible(false);
        sindicatoLbl.setVisible(false);

        extraLbl.setVisible(false);
        heuresextraLbl.setVisible(false);

        sousunionLbl.setVisible(false);
        //he.setVisible(false);
        // rateLbl.setVisible(false);

        //healthLbl.setVisible(false);
        //overtimeLbl.setVisible(false);
        //unionLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        language = new javax.swing.JComboBox<>();
        hoursTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        healthTF = new javax.swing.JTextField();
        assuranceLbl = new javax.swing.JLabel();
        hs = new javax.swing.JLabel();
        hf = new javax.swing.JLabel();
        he = new javax.swing.JLabel();
        tarifaLbl = new javax.swing.JLabel();
        rateLbl = new javax.swing.JLabel();
        tauxLbl = new javax.swing.JLabel();
        seguroLbl = new javax.swing.JLabel();
        healthLbl = new javax.swing.JLabel();
        sousunionLbl = new javax.swing.JLabel();
        unionTF = new javax.swing.JTextField();
        sindicatoLbl = new javax.swing.JLabel();
        unionLbl = new javax.swing.JLabel();
        weekly = new javax.swing.JButton();
        monthly = new javax.swing.JButton();
        annual = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        heuresextraLbl = new javax.swing.JLabel();
        extraLbl = new javax.swing.JLabel();
        overtimeLbl = new javax.swing.JLabel();
        overtimeTF = new javax.swing.JTextField();
        taxcreditLbl = new javax.swing.JLabel();
        taxCreditTF = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        entitlements = new javax.swing.JButton();

        jLabel13.setText("union subs");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        ok.setBackground(new java.awt.Color(153, 255, 51));
        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Select a language]", "english", "french", "spanish" }));

        assuranceLbl.setText("assurance maladie");

        hs.setText("horas");

        hf.setText("heures");

        he.setText("hours");

        tarifaLbl.setText("tarifa");

        rateLbl.setText("rate");

        tauxLbl.setText("taux");

        seguroLbl.setText("seguro de salud");

        healthLbl.setText("health insurance");

        sousunionLbl.setText("sous union");

        sindicatoLbl.setText(" sindicato subs");

        unionLbl.setText("union subs");

        weekly.setText("weekly pay");
        weekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyActionPerformed(evt);
            }
        });

        monthly.setText("monthly pay");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });

        annual.setText("annual pay");
        annual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annualActionPerformed(evt);
            }
        });

        jButton2.setText("Tax Refund calculator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        heuresextraLbl.setText("heures extra");

        extraLbl.setText("extra horas");

        overtimeLbl.setText("overtime");

        taxcreditLbl.setText("tax credit");

        add.setText("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setText("help?");

        entitlements.setText("My Entitlements");
        entitlements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entitlementsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 129, Short.MAX_VALUE)
                                .addComponent(taxcreditLbl)
                                .addGap(162, 162, 162)
                                .addComponent(taxCreditTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(he)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tarifaLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rateLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(tauxLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(healthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(assuranceLbl)
                                            .addComponent(seguroLbl))
                                        .addGap(28, 28, 28)
                                        .addComponent(healthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sindicatoLbl)
                                            .addComponent(unionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(unionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthly, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entitlements, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(annual, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ok))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sousunionLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(extraLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heuresextraLbl))
                            .addComponent(overtimeLbl, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(452, 452, 452)
                        .addComponent(overtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hoursTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hs)
                        .addComponent(hf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(he)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarifaLbl)
                            .addComponent(rateLbl)
                            .addComponent(tauxLbl)
                            .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(weekly)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(assuranceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(seguroLbl)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(healthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monthly)
                        .addComponent(healthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(sousunionLbl))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sindicatoLbl)
                                        .addComponent(unionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(annual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(unionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heuresextraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overtimeLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxcreditLbl)
                            .addComponent(taxCreditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(jButton1)))
                    .addComponent(entitlements))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void weeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyActionPerformed
        for (int i = 0; i < aList.size(); i++) {

            JOptionPane.showMessageDialog(null, "\n weekly payment details: " + aList.get(i).weekly());
            if (aList.get(i).gross() == 0.0 || aList.get(i).taxablePay() == 0.0 || aList.get(i).prsi() == 0.0) {// IF GROOS, PRSI EQUAL TO ZERO MEANS THE FIANCIAL DETAILS are NOT ENTERED BY THE USER
                JOptionPane.showMessageDialog(null, " hello, finacial details are empty" + "" + "\n   please enter financial details ");
            }

        }
    }//GEN-LAST:event_weeklyActionPerformed
*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new taxGUI().setVisible(false);
        new taxRefundGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (language.getSelectedIndex() == 1) {
            he.setVisible(true);
            rateLbl.setVisible(true);
            healthLbl.setVisible(true);
            overtimeLbl.setVisible(true);
            unionLbl.setVisible(true);

            hf.setVisible(false);
            tauxLbl.setVisible(false);
            assuranceLbl.setVisible(false);
            heuresextraLbl.setVisible(false);
            sousunionLbl.setVisible(false);

            hs.setVisible(false);
            tarifaLbl.setVisible(false);
            seguroLbl.setVisible(false);
            sindicatoLbl.setVisible(false);
            extraLbl.setVisible(false);
        };
        if (language.getSelectedIndex() == 2) {
            hf.setVisible(true);
            tauxLbl.setVisible(true);
            assuranceLbl.setVisible(true);
            heuresextraLbl.setVisible(true);
            sousunionLbl.setVisible(true);

            he.setVisible(false);
            rateLbl.setVisible(false);
            healthLbl.setVisible(false);
            overtimeLbl.setVisible(false);
            unionLbl.setVisible(false);

            hs.setVisible(false);
            tarifaLbl.setVisible(false);
            seguroLbl.setVisible(false);
            sindicatoLbl.setVisible(false);
            extraLbl.setVisible(false);
        };
        if (language.getSelectedIndex() == 3) {
            hs.setVisible(true);
            tarifaLbl.setVisible(true);
            seguroLbl.setVisible(true);
            sindicatoLbl.setVisible(true);
            extraLbl.setVisible(true);

            he.setVisible(false);
            rateLbl.setVisible(false);
            healthLbl.setVisible(false);
            overtimeLbl.setVisible(false);
            unionLbl.setVisible(false);

            hf.setVisible(false);
            tauxLbl.setVisible(false);
            assuranceLbl.setVisible(false);
            heuresextraLbl.setVisible(false);
            sousunionLbl.setVisible(false);
        };
    }//GEN-LAST:event_okActionPerformed

    private void entitlementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entitlementsActionPerformed
        new taxGUI().setVisible(false);
        new entitelementGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_entitlementsActionPerformed

    private void annualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annualActionPerformed
        
            aList.get(aList.size() -1).weekly();
            aList.get(aList.size() -1).monthly();

            JOptionPane.showMessageDialog(null, "\n annual payment details: " + aList.get(aList.size() -1).annual());
System.out.println(""+  + aList.get(aList.size() -1).netpay2());
        
    }//GEN-LAST:event_annualActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        
            
         aList.get(aList.size() -1).weekly();
           JOptionPane.showMessageDialog(null, "\n monthly payment details: " + aList.get(aList.size() -1).monthly());

        
    }//GEN-LAST:event_monthlyActionPerformed
private void weeklyActionPerformed(java.awt.event.ActionEvent evt) {                                       
       
//JOptionPane.showMessageDialog(null, "\n weekly payment details: " + aList.get(count-1).weekly());
            JOptionPane.showMessageDialog(null, "\n weekly payment details: " + aList.get(aList.size() -1).weekly());
            if (aList.get(aList.size() -1).gross() == 0.0 || aList.get(aList.size() -1).taxablePay() == 0.0 || aList.get(aList.size() -1).prsi() == 0.0) {// IF GROOS, PRSI EQUAL TO ZERO MEANS THE FIANCIAL DETAILS are NOT ENTERED BY THE USER
                JOptionPane.showMessageDialog(null, " hello, finacial details are empty" + "" + "\n   please enter financial details ");
            

        }
}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed



        p = new tax(); // CREATE AN INSTANCEC OF PAYROL CLASS
        // GET TEXT FROM TEXT FIELD

        hours = Double.parseDouble(hoursTF.getText());
        rate = Double.parseDouble(rateTF.getText());
        taxCredit = Double.parseDouble(taxCreditTF.getText());
        healthInsurance = Double.parseDouble(healthTF.getText());
        unionSubs = Double.parseDouble(unionTF.getText());
        overTime = Double.parseDouble(overtimeTF.getText());
        // PASS VALUES OF  VARIABELS  TO INSTACE OF CLASS P

        p.setHours(hours);
        p.setRate(rate);
        p.setOverTime(overTime);
        //   p.setTaxablePay(taxCredit);
        p.setUsc(usc);
        p.setTaxCredit(taxCredit);
        p.setUnionSubs(unionSubs);
        p.setHealthInsurance(healthInsurance);
p.netpay2();
        aList.add(p); // ADD ALL VALUES TO ARRAYLIST

        System.out.println("alist: " + aList.toString());
        count++;
        writeToFile();
        
    }//GEN-LAST:event_addActionPerformed
public void writeToFile(){
        try{
            File a= new File("output.dat");//declare and create file object
            FileOutputStream b = new FileOutputStream(a);//
            ObjectOutputStream c = new ObjectOutputStream(b);
            // write the object
            c.writeObject(aList);//log declared earlier
            //close the output stream
            c.close();
        }
        
        catch(IOException e){
            System.out.println(e);
        }
    }
    public void readFromFile(){
        try{
            File a = new File ("output.dat");
            FileInputStream b= new FileInputStream(a);
            ObjectInputStream c= new ObjectInputStream(b);
            // read the object from the file  array of object here called Log
            // convert prob   > cast it to remind it is a employee
            aList=(ArrayList<tax>)c.readObject();
            c.close();
            
            
        }
        catch (IOException|ClassNotFoundException ex){
            System.out.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taxGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton annual;
    private javax.swing.JLabel assuranceLbl;
    private javax.swing.JButton entitlements;
    private javax.swing.JLabel extraLbl;
    private javax.swing.JLabel he;
    private javax.swing.JLabel healthLbl;
    private javax.swing.JTextField healthTF;
    private javax.swing.JLabel heuresextraLbl;
    private javax.swing.JLabel hf;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JLabel hs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JComboBox<String> language;
    private javax.swing.JButton monthly;
    private javax.swing.JButton ok;
    private javax.swing.JLabel overtimeLbl;
    private javax.swing.JTextField overtimeTF;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTF;
    private javax.swing.JLabel seguroLbl;
    private javax.swing.JLabel sindicatoLbl;
    private javax.swing.JLabel sousunionLbl;
    private javax.swing.JLabel tarifaLbl;
    private javax.swing.JLabel tauxLbl;
    private javax.swing.JTextField taxCreditTF;
    private javax.swing.JLabel taxcreditLbl;
    private javax.swing.JLabel unionLbl;
    private javax.swing.JTextField unionTF;
    private javax.swing.JButton weekly;
    // End of variables declaration//GEN-END:variables
}
